########################################
# Spring Boot / Keycloak Configuration
########################################
keyclock:
  realm: ineat-realm
  auth-server-url: http://localhost:8180/auth
  resource: ineat-api
  credentials:
    secret: 4318bac2-c7ff-44e1-9cb2-fc1e97bdb549
  bearer-only: true
security:
  basic:
    enabled: false

